const Map<String, String> translationsEnUs = {
  'Profile': 'Profile',
  'Change': 'Change',
  'Change language': 'Change language',
  'Change PIN': 'Change PIN',
  'Email': 'Email',
  'Name': 'Name',
  'Phone number': 'Phone number',
  'Birth date': 'Birth date',
  'English': 'English',
  'Indonesia': 'Indonesia',
  'Your have verified your ID card': 'Your have verified your ID card',
  'Verify your ID card now!': 'Verify your ID card now!',
  'Account info': 'Account info',
  'Rating': 'Rating',
  'Other info': 'Other info',
  'Device Info': 'Device Info',
  'Version': 'Version',
  'Rate Now': 'Rate Now',
  'PIN wrong': 'PIN wrong',
  'chances left.': 'chances left',
  'Login to continue!': 'Login to continue!',
  'Email Address': 'Email Address',
  'Password': 'Password',
  'Login': 'Login',
  'Forgot Password?': 'Forgot Password?',
  'Or': 'Or',
  'Login With ': 'Login With ',
  'Enter email address to change your password':
      'Enter email address to change your password',
  'Cancel': 'Cancel',
  'Change Password': 'Change Password',
  'Searching your location': 'Searching your location',
  'Location Data Found': 'Location Data Found',
  'Auto Next In': 'Auto Next In',
  'Available Promo': 'Available Promo',
  'All Menu': 'All Menu',
  'all menu': 'all menu',
  'Orders prepared': 'Orders prepared',
  'Food': 'Food',
  'Beverages': 'Beverages',
  'Home': 'Home',
  'Orders': 'Orders',
  'Promo Name': 'Promo Name',
  'Terms and Conditions': 'Terms and Conditions',
  'Price': 'Price',
  'Level': 'Level',
  'Topping': 'Topping',
  'Notes': 'Notes',
  'Menu Detail': 'Menu Detail',
  'On Progress': 'On Progress',
  'History': 'History',
  'Start making orders.\n\nYour order\nwill show up here so\nyou can find\nyour favourite menu again!':
      'Start making orders.\n\nYour order\nwill show up here so\nyou can find\nyour favourite menu again!',
  'Already Order?\nTrace your orders\nhere':
      'Already Order?\nTrace your orders\nhere',
  'Empty Stock': 'Empty Stock',
  'Add Notes': 'Add Notes',
  'Add to Order': 'Add to Order',
  'Total Orders ': 'Total Orders ',
  'Discount 20%': 'Discount 20%',
  'Payment': 'Payment',
  'Choose Voucher': 'Choose Voucher',
  'Payment Total': 'Payment Total',
  'Order Now': 'Order Now',
  'Order Verification': 'Order Verification',
  'Enter your PIN': 'Enter your PIN',
  'Order Prepared': 'Order Prepared',
  'You can track your orders in': 'You can track your orders in',
  'Ok': 'Ok',
  'Canceled': 'Canceled',
  'Done': 'Done',
  'Order Again': 'Order Again',
  'Give Rating': 'Rate',
  'All Status': 'All Status',
  'Order Complete': 'Order Complete',
  'Order Canceled': 'Order Canceled',
  'Order Recieved': 'Order Recieved',
  'Please Take': 'Please Take',
  'Search': 'Search',
  'Are you going to cancel this order?': 'Are you going to cancel this order?',
  'Yes': 'Yes',
  'No': 'No',
  "Are you sure to update this order status?":
      "Are you sure to update this order status?",
  'No Order Canceled Yet': 'No Order Canceled Yet',
  'No Order Completed Yet': 'No Order Completed Yet',
  'Order Completed': 'Order Completed',
  'Order Added': 'Order Added',
  'Prepared': 'Prepared',
  'Voucher Detail': 'Voucher Detail',
  ' Orders': ' Orders',
  'Sugar Level': 'Sugar Level',
  'No Topping': 'No Topping',
  'Sausage': 'Sausage',
  'Add Note': 'Add Note',
  'Choose Topping': 'Choose Topping',
  'Choose Levels': 'Choose Levels',
  'Order Empty!': 'Order Empty!',
  'Delete': 'Delete',
  'Save': 'Save',
  'Use Voucher': 'Use Voucher',
  'Voucher cannot be combined with ': 'Voucher cannot be combined with ',
  "Discount Info": "Discount Info",
  "Fill Survey": 'Fill Survey',
  "Late <3x": 'Late <3x',
  'Value is required': 'Value is required',
  'Snack': 'Snack',
  'Order Created Succesfully': 'Order Created Succesfully',
  'Success': 'Success',
  'makanan': 'food',
  'minuman': 'beverages',
  'snack': 'snack',
  'Tambahkan Catatan': 'Add Notes',
  'Tanpa Toping': 'Without Topping',
  'Tidak ada order ditemukan di tanggal tersebut':
      'No order found in that date',
  'Privacy Policy': 'Privacy Policy',
  'Anda Yakin Untuk Logout?': 'Are You Sure?',
};
