const Map<String, String> translationsIdId = {
  'Profile': 'Profil',
  'Change': 'Ubah',
  'Change language': 'Ubah bahasa',
  'Change PIN': 'Ubah PIN',
  'Email': 'Alamat Email',
  'Name': 'Nama',
  'Phone number': 'No. telepon',
  'Birth date': 'Tanggal lahir',
  'English': 'Inggris',
  'Indonesia': 'Indonesia',
  'Your have verified your ID card': ' KTP anda sudah terverifikasi',
  'Verify your ID card now!': 'Verifikasi KTP mu sekarang!',
  'Account info': 'Info Akun',
  'Rating': 'Penilaian',
  'Other info': 'Info Lainnya',
  'Device Info': 'Info Perangkat',
  'Version': 'Versi',
  'Rate Now': 'Nilai Sekarang',
  'PIN wrong': 'Pin Salah',
  'chances left.': 'Kesempatan tersedia',
  'Login to continue!': 'Masuk untuk melanjutkan!',
  'Email Address': 'Alamat Email',
  'Password': 'Kata Sandi',
  'Login': 'Masuk',
  'Forgot Password?': 'Lupa Password?',
  'Or': 'Atau',
  'Login With ': 'Masuk Menggunakan ',
  'Enter email address to change your password':
      'Masukkan alamat email untuk mengubah password anda',
  'Cancel': 'Batal',
  'Change Password': 'Ubah Password',
  'Location Data Found': 'Data Lokasi Ditemukan',
  'Auto Next In': 'Otomatis Lanjut Dalam',
  'Available Promo': 'Promo yang Tersedia',
  'All Menu': 'Semua Menu',
  'all menu': 'semua menu',
  'Food': 'Makanan',
  'Beverages': 'Minuman',
  'Home': 'Beranda',
  'Orders': 'Pesanan',
  'Promo Name': 'Nama Promo',
  'Terms and Conditions': 'Syarat dan Ketentuan',
  'Price': 'Harga',
  'Level': 'Tingkat',
  'Topping': 'Toping',
  'Notes': 'Catatan',
  'Menu Detail': 'Detail Menu',
  'On Progress': 'Sedang Berjalan',
  'History': 'Riwayat',
  'Start making orders.\n\nYour order\nwill show up here so\nyou can find\nyour favourite menu again!':
      'Mulai buat pesanan.\n\nMakanan yang kamu pesan\nakan muncul di sini agar\nkamu bisa menemukan\nmenu favoritmu lagi!',
  'Already Order?\nTrace your orders\nhere':
      'Sudah Pesan?\nLacak pesananmu\ndi sini.',
  'Empty Stock': 'Stok Habis',
  'Add Notes': 'Tambahkan Catatan',
  'Add to Order': 'Tambahkan Ke Pesanan',
  'Total Orders ': 'Total Pesanan ',
  'Orders prepared': 'Order Disiapkan',
  'Discount 20%': 'Diskon 20%',
  'Payment': 'Pembayaran',
  'Choose Voucher': 'Pilih Voucher',
  'Payment Total': 'Total Pembayaran',
  'Order Now': 'Pesan Sekarang',
  'Order Verification': 'Verifikasi Pesanan',
  'Enter your PIN': 'Masukkan kode PIN',
  'Order Prepared': 'Pesanan Sedang Disiapkan',
  'You can track your orders in': 'Kamu dapat melacak pesananmu di fitur',
  'Ok': 'Oke',
  'Canceled': 'Dibatalkan',
  'Done': 'Selesai',
  'Order Again': 'Pesan Lagi',
  'Give Rating': 'Beri Penilaian',
  'All Status': 'Semua Status',
  'Order Complete': 'Pesanan Selesai',
  'Order Canceled': 'Pesanan Dibatalkan',
  'Order Recieved': 'Pesanan Diterima',
  'Please Take': 'Silahkan Diambil',
  'Search': 'Pencarian',
  'Are you going to cancel this order?':
      'Apakah anda ingin membatalkan pesanan?',
  'Yes': 'Ya',
  'No': 'Tidak',
  "Are you sure to update this order status?":
      "Apakah anda yakin akan mengubah status Pesanan ini?",
  'No Order Canceled Yet': 'Belum ada pesanan Dibatalkan',
  'No Order Completed Yet': 'Belum ada pesanan Selesai',
  'Order Added': 'Order Ditambahkan',
  'Prepared': 'Disiapkan',
  'Voucher Detail': 'Detail Voucher',
  ' Orders': ' Pesanan',
  'Sugar Level': 'Tingkat Gula',
  'No Topping': 'Tanpa Toping',
  'Sausage': 'Sosis',
  'Add Note': 'Buat Catatan',
  'Choose Topping': 'Pilih Toping',
  'Choose Levels': 'Pilih Tingkatan',
  'Order Empty!': 'Pesanan Kosong!',
  'Delete': 'Hapus',
  'Save': 'Simpan',
  'Use Voucher': 'Pakai Voucher',
  'Voucher cannot be combined with ':
      'Penggunaan voucher tidak dapat digabung dengan ',
  "Discount Info": "Info Diskon",
  "Fill Survey": 'Mengisi Survey',
  "Late <3x": 'Terlambat <3x',
  'Value is required': 'Data harus diisi',
  'Snack': 'Snack',
  'Order Created Succesfully': 'Pesanan Berhasil Dibuat',
  'Success': 'Berhasil',
  'Order Completed': 'Pesanan Selesai',
};
