// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1Igboq-GAfqppKAnJ4rGykLdX1Ia-7Q4',
    appId: '1:444590361239:web:35c1ac52b89964986077d2',
    messagingSenderId: '444590361239',
    projectId: 'venturo-trainee-9c97f',
    authDomain: 'venturo-trainee-9c97f.firebaseapp.com',
    storageBucket: 'venturo-trainee-9c97f.appspot.com',
    measurementId: 'G-D5ZM5FSBBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgsQZJFDychao7hrr2mqD2wXIqisStGtg',
    appId: '1:444590361239:android:4bb359af966245d86077d2',
    messagingSenderId: '444590361239',
    projectId: 'venturo-trainee-9c97f',
    storageBucket: 'venturo-trainee-9c97f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnzlzJVQ1ljRdoLHGthvehV_JFhlUDT_s',
    appId: '1:444590361239:ios:6facfd5f8f44d9646077d2',
    messagingSenderId: '444590361239',
    projectId: 'venturo-trainee-9c97f',
    storageBucket: 'venturo-trainee-9c97f.appspot.com',
    iosBundleId: 'com.example.venturoFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnzlzJVQ1ljRdoLHGthvehV_JFhlUDT_s',
    appId: '1:444590361239:ios:6facfd5f8f44d9646077d2',
    messagingSenderId: '444590361239',
    projectId: 'venturo-trainee-9c97f',
    storageBucket: 'venturo-trainee-9c97f.appspot.com',
    iosBundleId: 'com.example.venturoFood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1Igboq-GAfqppKAnJ4rGykLdX1Ia-7Q4',
    appId: '1:444590361239:web:7335988c787421456077d2',
    messagingSenderId: '444590361239',
    projectId: 'venturo-trainee-9c97f',
    authDomain: 'venturo-trainee-9c97f.firebaseapp.com',
    storageBucket: 'venturo-trainee-9c97f.appspot.com',
    measurementId: 'G-JQLHF9158Q',
  );
}
